### ISSUE TITLE
成果物

### ISSUE THREAD

**Issue by tomoki0715** [furuhashilab/V-F_UN-Validation#5]
![IMG_1125](https://github.com/furuhashilab/V-F_UN-Validation/assets/108712041/d3cd2ef6-becb-4309-a331-f7307e77f9fd)
![IMG_1126 2](https://github.com/furuhashilab/V-F_UN-Validation/assets/108712041/2dfa6694-50b1-4c1c-9c6e-4eb22c4adf65)
![IMG_1127](https://github.com/furuhashilab/V-F_UN-Validation/assets/108712041/ab928000-14bd-44dd-937f-1595943597e9)

**Comment by tomoki0715** [comment]
![vf_UN-Validation_UN-Validation_UN-Validation](https://github.com/furuhashilab/V-F_UN-Validation/assets/108712041/dc0a2a90-f46c-4190-839f-561dc3da321e)

**Comment by tomoki0715** [comment]
![vf_UN-Validation_UN-Validation_UN-Validation](https://github.com/furuhashilab/V-F_UN-Validation/assets/108712041/010d0104-b27f-413b-b2d0-d0a71fce02d8)

**Comment by tomoki0715** [comment]
<img width="854" alt="スクリーンショット 2024-07-02 11 08 45" src="https://github.com/furuhashilab/V-F_UN-Validation/assets/108712041/16ae6850-d2e4-4903-98a5-49a2314c6f8e">

**Comment by tomoki0715** [comment]
<img width="1440" alt="スクリーンショット 2024-07-02 11 10 32" src="https://github.com/furuhashilab/V-F_UN-Validation/assets/108712041/614a855d-7818-47c4-9b33-7211221a66b4">

**Comment by tomoki0715** [comment]
<img width="854" alt="スクリーンショット 2024-07-02 11 08 45" src="https://github.com/furuhashilab/V-F_UN-Validation/assets/108712041/e118a5e5-6e34-4df6-b501-7ee5d54503a3">

**Comment by tomoki0715** [comment]
<img width="1440" alt="スクリーンショット 2024-07-02 11 10 32" src="https://github.com/furuhashilab/V-F_UN-Validation/assets/108712041/c8fa341d-80e1-490f-9f61-dfc169636315">

**Comment by Fuka-Okamura** [comment]
HOT tasking Manager でValidationを行う際に必要なときがあるJOSMのインストール＆設定方法
https://medium.com/furuhashilab/hot-tasking-manager%E3%81%AEvalidation%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8Bjosm%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9-youth%E2%91%A0%E9%80%B1%E5%A0%B1-b637c242f2a5
